# Generated by Django 3.0.3 on 2020-02-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('history', models.CharField(max_length=10000)),
                ('physical_examination', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
